variables:
  GIT_SUBMODULE_STRATEGY: recursive

buildAndDeployApkUnstable:
  stage: build
  script:
    - sh deploy-unstable.sh
  only:
    - tags
  when: manual
  needs: []
  allow_failure: true
  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - app/build/outputs/apk/unstable/release/*.apk

buildAndDeployApkStable:
  stage: build
  script:
    - sh deploy-stable.sh
  only:
    - tags
  when: manual
  needs: []
  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - app/build/outputs/apk/stable/release/*.apk

buildAndDeployPlaystore:
  stage: deploy
  script:
    - sh build-playstore.sh
    - bash tools/venv_playstore.sh
    - . .venv-playstore/bin/activate
    - python publish_playstore.py --sa /root/grayjay.json --package com.futo.platformplayer.playstore --aab ./app/build/outputs/bundle/playstoreRelease/app-playstore-release.aab --track production --status completed
  only:
    - tags
  when: on_success
  needs:
    - buildAndDeployApkStable
  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - app/build/outputs/bundle/playstoreRelease/*.aab

updateFdroidRepo:
  stage: deploy
  only:
    - tags
  when: on_success
  needs:
    - job: buildAndDeployApkStable
      artifacts: true
  script:
    - python3 update_fdroid_index.py
