pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        // Polycentric Kotlin SDK, published by the Harbor Gitlab project.
        // TODO: when the Harbor Forgejo project publishes the SDK, switch to that URL.
        maven { url 'https://gitlab.futo.org/api/v4/projects/42/packages/maven' }
    }
}

includeBuild('dep/polycentricandroid') {
    dependencySubstitution {
        substitute module('com.polycentric.core:app') using project(':app')
    }
}

includeBuild('dep/futopay/android') {
    dependencySubstitution {
        substitute module('com.futo.futopay:app') using project(':app')
    }
}

rootProject.name = "FutoVideo"
include ':app'
