syntax = "proto3";

package com.futo.platformplayer.polycentric;

option java_package = "com.futo.platformplayer.polycentric";
option java_multiple_files = true;

// Polycentric v1 wire format, kept such that signing keys created for v1 can
// still be decoded and used in Polycentric v2. Note that the v1 `Process`
// (16 random bytes) is written for parity but is not used in v2.

message PrivateKey {
  uint64 key_type = 1;
  bytes key = 2;
}

message Process {
  bytes process = 1;
}

message StorageTypeProcessSecret {
  PrivateKey system = 1;
  Process process = 2;
}
